set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSROOT "")

set(CMAKE_C_LINK_EXECUTABLE 
	"<CMAKE_LINKER> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> \
	<OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang)
set(CMAKE_ASM_COMPILER clang)
#set(CMAKE_LINKER_TYPE LLD)

add_compile_options(
	$<$<COMPILE_LANGUAGE:C,CXX>:-target>
	$<$<COMPILE_LANGUAGE:C,CXX>:x86_64-unknown-linux-elf>
)
